# Site settings
title: Icons of slovenian design
email: masa.cernovsek@gmail.com
description: "Icons of slovenian design presented as UI icons"
baseurl: "/icons-design"
url: "http://masacernovsek.si/icons-design/"


# Build settings
markdown: kramdown
permalink: pretty


sass:
    sass_dir: assets/stylesheet/_sass
    style: compressed